#!/bin/bash
# GlacierFarm - Quick Commands Reference
# Run this file to see all available commands

echo "=========================================="
echo "  🌾 GlacierFarm - Quick Commands"
echo "=========================================="
echo ""
echo "📋 SETUP & INSTALLATION"
echo "  npm run install-all      - Install all dependencies"
echo ""
echo "🚀 RUNNING"
echo "  npm run dev              - Start dev server (localhost:3000)"
echo "  npm start                - Preview production build"
echo ""
echo "🧪 TESTING"
echo "  npm test                 - Run all tests"
echo "  npm run test:ui          - Run tests with UI"
echo ""
echo "📦 BUILD"
echo "  npm run build            - Build for production"
echo ""
echo "🔍 CODE QUALITY"
echo "  npm run lint             - Check code with ESLint"
echo ""
echo "📄 ENVIRONMENT"
echo "  cp .env.example .env     - Create .env file"
echo "  Edit .env with your MongoDB URI and API URL"
echo ""
echo "=========================================="
echo ""
echo "📊 CURRENT STATUS"
echo "✅ Server: Fully functional"
echo "✅ UI: Modernized with Tailwind CSS"
echo "✅ Tests: 6/6 passing"
echo "✅ Dev Server: Running at http://localhost:3000"
echo "⏳ Environment: Needs configuration"
echo ""
echo "=========================================="
echo ""
echo "🎯 QUICK START"
echo "1. cp .env.example .env"
echo "2. Edit .env file"
echo "3. npm run dev"
echo "4. Open http://localhost:3000"
echo "5. npm test (to run tests)"
echo ""
echo "=========================================="
